### ISSUE TITLE
Fix terraform security group

### ISSUE THREAD

**Issue by netflash** [cloudreach/aws-lambda-es-cleanup#15]
Current security group doesn't allow DNS requests, therefor lambda function can't resolve ES cluster DNS name.

```
('Connection aborted.', gaierror(-3, 'Temporary failure in name resolution')): ConnectionError
Traceback (most recent call last):
File "/var/task/es-cleanup.py", line 180, in lambda_handler
for index in es.get_indices():
File "/var/task/es-cleanup.py", line 165, in get_indices
return self.send_to_es("/_cat/indices")
File "/var/task/es-cleanup.py", line 119, in send_to_es
res = session.send(preq)
File "/var/runtime/botocore/vendored/requests/sessions.py", line 573, in send
r = adapter.send(request, **kwargs)
File "/var/runtime/botocore/vendored/requests/adapters.py", line 415, in send
raise ConnectionError(err, request=request)
botocore.vendored.requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(-3, 'Temporary failure in name resolution'))
```

**Comment by giuliocalzo** [comment]
Thanks @netflash for you feedback!
